<?php

/**
 * @file
 * Contains vacancy_importer.module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\node\Entity\Node;

/**
 * Implements hook_entity_delete().
 */
function vacancy_importer_entity_delete(EntityInterface $entity) {
  // Only act on content entities.
  if (!($entity instanceof FieldableEntityInterface)) {
    return;
  }

  // Delete the node-source relation.
  if ($entity instanceof Node && $entity->getType() == 'vacancy') {
    /** @var \Drupal\vacancy_importer\VacancyImporter $importer */
    $importer = \Drupal::service('vacancy.importer');
    $importer->deleteNodeSourceRelation($entity->id());
  }
}

/**
 * Implements hook_cron().
 */
function vacancy_importer_cron() {
  $request_time = \Drupal::time()->getRequestTime();

  // Import new vacancies and clean up old vacancies.
  $cron_config = \Drupal::config('vacancy_importer.settings')->get('cron');

  if (!empty($cron_config['enabled'])) {
    $interval = !empty($cron_config['interval']) ? $cron_config['interval'] : 1800;
    $next_execution = \Drupal::state()->get('vacancy_importer.next_execution', 0);

    if ($request_time >= $next_execution) {
      // Execute import.
      \Drupal::logger('vacancy_importer')->notice('Executing vacancy import.');
      /** @var \Drupal\vacancy_importer\VacancyImporter $importer */
      $importer = \Drupal::service('vacancy.importer');
      $importer->execute();

      // Clean up old unpublished vacancies.
      \Drupal::logger('vacancy_importer')->notice('Executing cleanup of old unpublished vacancies.');
      $importer->cleanupOldVacancies();

      \Drupal::state()->set('vacancy_importer.next_execution', $request_time + $interval);
    }
  }

  // Archive due vacancies.
  $archive_config = \Drupal::config('vacancy_importer.settings')->get('archive');

  if (!empty($archive_config['enabled'])) {
    $interval = !empty($archive_config['interval']) ? $archive_config['interval'] : 900;
    $next_execution = \Drupal::state()->get('vacancy_importer.next_archive_execution', 0);

    if ($request_time >= $next_execution) {
      \Drupal::logger('vacancy_importer')->notice('Executing archiving of due published vacancies.');
      /** @var \Drupal\vacancy_importer\VacancyImporter $importer */
      $importer->archiveDueVacancies();

      \Drupal::state()->set('vacancy_importer.next_archive_execution', $request_time + $interval);
    }
  }
}
